#!/usr/bin/env bash
# This script displays on the 4 and then "bad luck from China"
# on the 4th iteration, 9 and then bad luck from Japan for the
# 9th loop iteration, 17 and then bad luck from Italy
# for the 17th loop iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in 
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	((i++))
done
