#!/usr/bin/env bash
# script that displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash
# is displayed (refer to the example)
list=$(ls)
for item in $list; do
	echo "$item" | cut -d '-' -f2
done
